LOGGING_LEVEL = 'DEBUG'

TOKEN = '1907978319:AAF9ObvJwFekyuFQwuJJTCsS64VI9NTR9Dg'

SPBU_TT_API_REQUEST_TIMEOUT = '20'

DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASSWORD = 'postgres'
DB_PORT = '5432'
DB_SCHEMA = 'bot'
DB_HOST = 'localhost'
DB_MIGRATIONS_TABLE = 'migrations'

SCHEDULER_TIME = "14:00"